### ISSUE TITLE
Alex doesn't fix his issues

### ISSUE THREAD

**Issue by kyroschow** [TheCompSciNoob/MinigameMarathon#20]
Alex fix this

**Comment by alexanderberry** [comment]
true

**Comment by alexanderberry** [comment]
Fixed by ecf10fec7b94e987a42bb896f470c26eb0fb5ad8

**Comment by alexanderberry** [comment]
issue reemerged with MathGame class

**Comment by kyroschow** [comment]
@hedgey579 what a nasty old bug

**Comment by kyroschow** [comment]
fixed by cd222b3d17a41ff9d2c0d1b166460527605ffc39
