### ISSUE TITLE
BinaryGame eval mechanic needs to be changed

### ISSUE THREAD

**Issue by alexanderberry** [TheCompSciNoob/MinigameMarathon#22]
Change from completion to time based.

**Comment by alexanderberry** [comment]
Fixed by 77638a7e30f036362f9b60779b0d60b15138b7be

Eval mechanic is error based. Pending change

**Comment by kyroschow** [comment]
time is not used in score evaluation mechanic even though the time is accessed. @hedgey579 Bug?

**Comment by alexanderberry** [comment]
>time is not used in score evaluation mechanic even though the time is accessed.

Moved to #50.
