### ISSUE TITLE
arrows dont look good in maze

### ISSUE THREAD

**Issue by kyroschow** [TheCompSciNoob/MinigameMarathon#29]
[Escalator.zip](https://github.com/TheCompSciNoob/MinigameMarathon/files/1553833/Escalator.zip)
here's some good ones

**Comment by alexanderberry** [comment]
Will add

**Comment by kyroschow** [comment]
but they have all the vectors put on the same image 
how do you separate them? @hedgey579

**Comment by alexanderberry** [comment]
I'm going to use a vector editor

**Comment by kyroschow** [comment]
completed
