### ISSUE TITLE
Color Game Colored Buttons

### ISSUE THREAD

**Issue by Chrysopelea-Rc** [TheCompSciNoob/MinigameMarathon#38]
Does anyone know how to make the buttons colorful?

**Comment by Chrysopelea-Rc** [comment]
here is a link.
https://stackoverflow.com/questions/4602902/how-to-set-the-text-color-of-textview-in-code

**Comment by Chrysopelea-Rc** [comment]
https://stackoverflow.com/questions/4499208/android-setting-text-view-color-from-java-code

**Comment by kyroschow** [comment]
You have found the solution
