### ISSUE TITLE
POWERPOINT?!

### ISSUE THREAD

**Issue by Chrysopelea-Rc** [TheCompSciNoob/MinigameMarathon#39]
I will be making a google presentation and  here is the link. Please Contribute your part!

https://docs.google.com/presentation/d/1Z6aPHg6RBJ7NE400lBpbcx2ncF02edkZKPdQSG3bne4/edit#slide=id.p

**Comment by alexanderberry** [comment]
gut

**Comment by kyroschow** [comment]
I requested access please add me

**Comment by alexanderberry** [comment]
@TheCompSciNoob what code are we featuring for the powerpoint?

**Comment by kyroschow** [comment]
maze generation
falling edge nav drawer
HighScoreTabFragment cuz it's complicated
@hedgey579 what else

**Comment by alexanderberry** [comment]
Async callbacks in `BackendlessHandler`
https://github.com/TheCompSciNoob/MinigameMarathon/blob/e2334975e85a5e3c4b3503d62de6589571b635b2/app/src/main/java/com/example/chow/minigamemarathon/BackendlessHandler.java#L85-L98
Database schemas and functions in `DatabaseHandler`
https://github.com/TheCompSciNoob/MinigameMarathon/blob/e2334975e85a5e3c4b3503d62de6589571b635b2/app/src/main/java/com/example/chow/minigamemarathon/DatabaseHandler.java#L65-L78
and
https://github.com/TheCompSciNoob/MinigameMarathon/blob/e2334975e85a5e3c4b3503d62de6589571b635b2/app/src/main/java/com/example/chow/minigamemarathon/DatabaseHandler.java#L35-L40
Maybe the network status stuff.
https://github.com/TheCompSciNoob/MinigameMarathon/blob/e2334975e85a5e3c4b3503d62de6589571b635b2/app/src/main/java/com/example/chow/minigamemarathon/BackendlessHandler.java#L117-L121
and
https://github.com/TheCompSciNoob/MinigameMarathon/blob/e2334975e85a5e3c4b3503d62de6589571b635b2/app/src/main/java/com/example/chow/minigamemarathon/WorldHighScoreFragment.java#L45-L70
i think that should be good
