### ISSUE TITLE
StackOverFlowError in maze

### ISSUE THREAD

**Issue by kyroschow** [TheCompSciNoob/MinigameMarathon#41]
replace recursion with stack

**Comment by kyroschow** [comment]
@hedgey579 it's all yours

**Comment by alexanderberry** [comment]
### Possible Solution
https://mitpress.mit.edu/sicp/full-text/sicp/book/node110.html

**Comment by alexanderberry** [comment]
https://stackoverflow.com/questions/159590/way-to-go-from-recursion-to-iteration
https://web.archive.org/web/20120227170843/http://cs.saddleback.edu/rwatkins/CS2B/Lab%20Exercises/Stacks%20and%20Recursion%20Lab.pdf

**Comment by alexanderberry** [comment]
https://www.codeproject.com/Articles/418776/How-to-replace-recursive-functions-using-stack-and

**Comment by kyroschow** [comment]
@hedgey579 I forgot to give you the algorithm I used:
http://weblog.jamisbuck.org/2010/12/27/maze-generation-recursive-backtracking
btw how's the replacing going?

**Comment by kyroschow** [comment]
fixed by c6a22c74c94189317e04298e42951fa71d74a898
