### ISSUE TITLE
Icon?

### ISSUE THREAD

**Issue by kyroschow** [TheCompSciNoob/MinigameMarathon#42]
@Chrysopelea-Rc need the icon for the app

**Comment by alexanderberry** [comment]
![logo2](https://user-images.githubusercontent.com/11507541/34188129-938e059e-e4e9-11e7-9d5d-baaa2e4c615b.png)

it's 64x64. maybe convert it to vector? @TheCompSciNoob

**Comment by kyroschow** [comment]
@hedgey579 how to convert?

**Comment by alexanderberry** [comment]
nvm i tried it doesn't work

**Comment by kyroschow** [comment]
![icon](https://user-images.githubusercontent.com/26610512/34191371-3b0fecae-e4fb-11e7-8719-1e82bb7b7857.png)
now this looks better
Still a png but it looks fine
what do you think @hedgey579

**Comment by kyroschow** [comment]
btw we should add rounded edges to the icon

**Comment by alexanderberry** [comment]
Legacy icon design guidelines
https://material.io/guidelines/style/icons.html
Fancy new adaptive icon design guidelines
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html

**Comment by kyroschow** [comment]
fixed by 42efc40961c8075cae604557aeaac9e631a1153f
