### ISSUE TITLE
Make How to Play Fragment

### ISSUE THREAD

**Issue by kyroschow** [TheCompSciNoob/MinigameMarathon#43]
Please give me a description of how the games are played

**Comment by alexanderberry** [comment]
- ColorGame: You are given three primary colors at the bottom of your screen and a secondary color in the center of your screen. Your goal is to make the secondary color with the primary colors provided.
- BinaryGame: You are given two buttons at the bottom of the screen and a string of numbers in the center. Your goal is to accurately type the string of numbers, however, both the string of numbers in the center and the buttons at the bottom will switch around during the course of play.
- LightsOutGame: @TheCompSciNoob i don't know how to play this except by spamming all the buttons until something happens.
- MazeGame: Get to the bottom of a 3d maze by going up or down stairs.

**Comment by kyroschow** [comment]
fixed by ecbbf6be25e0854836150861c0eefd204c6f869d
