### ISSUE TITLE
Make disable animation for the save button

### ISSUE THREAD

**Issue by alexanderberry** [TheCompSciNoob/MinigameMarathon#44]
`EndFragment`

**Comment by kyroschow** [comment]
### Possible Solution
\<selector xmlns:android="http://schemas.android.com/apk/res/android">
\<item android:state_pressed="true">
        \<shape>
        \<gradient
            android:startColor="@color/white"
            android:endColor="@color/light_gray"
            android:angle="270" />
        \<stroke
            android:width="3dp"
            android:color="@color/classic_red1" />
        \<corners
            android:radius="3dp" />
        \<padding
            android:left="10dp"
            android:top="10dp"
            android:right="10dp"
            android:bottom="10dp" />
    \</shape>

\</item>

\<item android:state_focused="true">
    \<shape>
        \<solid android:color="#424242" />  //another custom shape here for focus state
    \</shape>
\</item>

\<item>
    \<shape>
        \<gradient
            android:startColor="@color/classic_red1"
            android:endColor="@color/classic_red2"
            android:angle="270" />
        \<stroke
            android:width="2dp"
            android:color="@color/white" />
        \<corners
            android:radius="3dp" />
        \<padding
            android:left="10dp"
            android:top="10dp"
            android:right="10dp"
            android:bottom="10dp" />
    \</shape>

\</item>

**Comment by kyroschow** [comment]
fixed by 07448e4681da922c414ba7a8d0f881e8de9fcf11
