### ISSUE TITLE
Vectors display improperly

### ISSUE THREAD

**Issue by alexanderberry** [TheCompSciNoob/MinigameMarathon#46]
Vectors appear pixelated on Nexus devices.

**Comment by alexanderberry** [comment]
May be caused by lower API levels not having support for Material Design (introduced in API Level 20). Try making a separate set of .bmp files for API levels >20 and using the normal vectors for API levels >= 20. Add an API level check to implement this. @TheCompSciNoob

**Comment by kyroschow** [comment]
### Possible solution
https://stackoverflow.com/questions/34417843/how-to-use-vector-drawables-in-android-api-lower-21

**Comment by alexanderberry** [comment]
I think that's a better solution

**Comment by alexanderberry** [comment]
![image](https://user-images.githubusercontent.com/11507541/34188810-19715cee-e4ed-11e7-8c71-530c4a980a9c.png)

**Comment by alexanderberry** [comment]
Fixed by 5152dda2b82011606ac566fc6ff3e1aa5f5fe3b1. Added backwards compatibility for vectors.

**Comment by alexanderberry** [comment]
Nevermind

**Comment by kyroschow** [comment]
no need to fix

**Comment by kyroschow** [comment]
This is actually quite a problem @hedgey579 can you revert to a previous version

**Comment by kyroschow** [comment]
fixed by 794675a9d6a870d5414828c586a77241dd9752fe
