### ISSUE TITLE
"Save online" does not check for internet

### ISSUE THREAD

**Issue by kyroschow** [TheCompSciNoob/MinigameMarathon#55]
Should notify the user if there is no internet connection
Because then people would think your app sucks but the problem is that they have no internet connection
### Possible Solution
https://stackoverflow.com/questions/4238921/detect-whether-there-is-an-internet-connection-available-on-android

**Comment by alexanderberry** [comment]
Added by 7457c0318d3ca25010a3c671473c97364c398760.
