### ISSUE TITLE
Inefficient coding in LightsOutGameFragment

### ISSUE THREAD

**Issue by kyroschow** [TheCompSciNoob/MinigameMarathon#57]
the code in `LightsOutGameFragment` is overly complicated. We do not need `ViewTreeObserver` to do the layout.

**Comment by alexanderberry** [comment]
Implement functionality of `onPreDraw()`https://github.com/TheCompSciNoob/MinigameMarathon/blob/e2334975e85a5e3c4b3503d62de6589571b635b2/app/src/main/java/com/example/chow/minigamemarathon/LightsOutGameFragment.java#L129 and refactor references on https://github.com/TheCompSciNoob/MinigameMarathon/blob/e2334975e85a5e3c4b3503d62de6589571b635b2/app/src/main/java/com/example/chow/minigamemarathon/LightsOutGameFragment.java#L106

**Comment by kyroschow** [comment]
fixed by b2ab5cef27903e446769e12762950692cd59f958
