### ISSUE TITLE
Hook up Button to github repository in AboutFragment

### ISSUE THREAD

**Issue by kyroschow** [TheCompSciNoob/MinigameMarathon#58]
I put a TODO in `AboutFragment`

**Comment by kyroschow** [comment]
### Possible Solution
https://stackoverflow.com/questions/2201917/how-can-i-open-a-url-in-androids-web-browser-from-my-application

**Comment by kyroschow** [comment]
`Intent browserIntent = new Intent(Intent.ACTION_VIEW, Uri.parse("https://github.com/TheCompSciNoob/MinigameMarathon"));`
`startActivity(browserIntent);`

**Comment by alexanderberry** [comment]
will implement now

**Comment by kyroschow** [comment]
fixed by b1101ed7a4f63a930319fc237550c4d3bcca124e
