### ISSUE TITLE
Maze3D crashes app on certain devices

### ISSUE THREAD

**Issue by kyroschow** [TheCompSciNoob/MinigameMarathon#62]
Your issue may have already been reported! Please check the [issue tracker](https://github.com/TheCompSciNoob/MinigameMarathon/issues) before creating a new 
### Behavior
`Maze3D` crashes on lower api devices (regardless of difficulty)
#### Possible solution
idk because I can't check with the apk, probably `Stack`?
### Steps to reproduce the behavior
use a android 4.4.2 device and play the maze game
### Environment
OS Version (Version and API Level): android api 4.4.2

**Comment by alexanderberry** [comment]
Stack extends vector compat fix needed

**Comment by kyroschow** [comment]
issue caused by vector `Drawable`s
fixed by 1eb541061ab7b53106f97dcdbdf648740ba14a84
